/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from '../../src/routes/__root.tsx'
import { Route as VerifyRouteImport } from '../../src/routes/verify.tsx'
import { Route as TracksRouteImport } from '../../src/routes/tracks.tsx'
import { Route as SignupRouteImport } from '../../src/routes/signup.tsx'
import { Route as ProcessRouteImport } from '../../src/routes/process.tsx'
import { Route as PricingRouteImport } from '../../src/routes/pricing.tsx'
import { Route as LoginRouteImport } from '../../src/routes/login.tsx'
import { Route as ForgotPasswordRouteImport } from '../../src/routes/forgot-password.tsx'
import { Route as DashboardRouteImport } from '../../src/routes/dashboard.tsx'
import { Route as ContactRouteImport } from '../../src/routes/contact.tsx'
import { Route as ApplyRouteImport } from '../../src/routes/apply.tsx'
import { Route as AboutRouteImport } from '../../src/routes/about.tsx'
import { Route as IndexRouteImport } from '../../src/routes/index'
import { Route as DashboardIndexRouteImport } from '../../src/routes/dashboard.index.tsx'
import { Route as DashboardTrainingRouteImport } from '../../src/routes/dashboard.training.tsx'
import { Route as DashboardSettingsRouteImport } from '../../src/routes/dashboard.settings.tsx'
import { Route as DashboardResumeRouteImport } from '../../src/routes/dashboard.resume.tsx'
import { Route as DashboardProfileRouteImport } from '../../src/routes/dashboard.profile.tsx'
import { Route as DashboardJobsRouteImport } from '../../src/routes/dashboard.jobs.tsx'
import { Route as DashboardInterviewsRouteImport } from '../../src/routes/dashboard.interviews.tsx'
import { Route as DashboardCertificatesRouteImport } from '../../src/routes/dashboard.certificates.tsx'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksRoute = TracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTrainingRoute = DashboardTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResumeRoute = DashboardResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobsRoute = DashboardJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInterviewsRoute = DashboardInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCertificatesRoute = DashboardCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/process': typeof ProcessRoute
  '/signup': typeof SignupRoute
  '/tracks': typeof TracksRoute
  '/verify': typeof VerifyRoute
  '/dashboard/certificates': typeof DashboardCertificatesRoute
  '/dashboard/interviews': typeof DashboardInterviewsRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/resume': typeof DashboardResumeRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/training': typeof DashboardTrainingRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/process': typeof ProcessRoute
  '/signup': typeof SignupRoute
  '/tracks': typeof TracksRoute
  '/verify': typeof VerifyRoute
  '/dashboard/certificates': typeof DashboardCertificatesRoute
  '/dashboard/interviews': typeof DashboardInterviewsRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/resume': typeof DashboardResumeRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/training': typeof DashboardTrainingRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/process': typeof ProcessRoute
  '/signup': typeof SignupRoute
  '/tracks': typeof TracksRoute
  '/verify': typeof VerifyRoute
  '/dashboard/certificates': typeof DashboardCertificatesRoute
  '/dashboard/interviews': typeof DashboardInterviewsRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/resume': typeof DashboardResumeRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/training': typeof DashboardTrainingRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/apply'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/process'
    | '/signup'
    | '/tracks'
    | '/verify'
    | '/dashboard/certificates'
    | '/dashboard/interviews'
    | '/dashboard/jobs'
    | '/dashboard/profile'
    | '/dashboard/resume'
    | '/dashboard/settings'
    | '/dashboard/training'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apply'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/process'
    | '/signup'
    | '/tracks'
    | '/verify'
    | '/dashboard/certificates'
    | '/dashboard/interviews'
    | '/dashboard/jobs'
    | '/dashboard/profile'
    | '/dashboard/resume'
    | '/dashboard/settings'
    | '/dashboard/training'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/apply'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/process'
    | '/signup'
    | '/tracks'
    | '/verify'
    | '/dashboard/certificates'
    | '/dashboard/interviews'
    | '/dashboard/jobs'
    | '/dashboard/profile'
    | '/dashboard/resume'
    | '/dashboard/settings'
    | '/dashboard/training'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApplyRoute: typeof ApplyRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ProcessRoute: typeof ProcessRoute
  SignupRoute: typeof SignupRoute
  TracksRoute: typeof TracksRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks': {
      id: '/tracks'
      path: '/tracks'
      fullPath: '/tracks'
      preLoaderRoute: typeof TracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/training': {
      id: '/dashboard/training'
      path: '/training'
      fullPath: '/dashboard/training'
      preLoaderRoute: typeof DashboardTrainingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/resume': {
      id: '/dashboard/resume'
      path: '/resume'
      fullPath: '/dashboard/resume'
      preLoaderRoute: typeof DashboardResumeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jobs': {
      id: '/dashboard/jobs'
      path: '/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof DashboardJobsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/interviews': {
      id: '/dashboard/interviews'
      path: '/interviews'
      fullPath: '/dashboard/interviews'
      preLoaderRoute: typeof DashboardInterviewsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/certificates': {
      id: '/dashboard/certificates'
      path: '/certificates'
      fullPath: '/dashboard/certificates'
      preLoaderRoute: typeof DashboardCertificatesRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardCertificatesRoute: typeof DashboardCertificatesRoute
  DashboardInterviewsRoute: typeof DashboardInterviewsRoute
  DashboardJobsRoute: typeof DashboardJobsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardResumeRoute: typeof DashboardResumeRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTrainingRoute: typeof DashboardTrainingRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCertificatesRoute: DashboardCertificatesRoute,
  DashboardInterviewsRoute: DashboardInterviewsRoute,
  DashboardJobsRoute: DashboardJobsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardResumeRoute: DashboardResumeRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTrainingRoute: DashboardTrainingRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApplyRoute: ApplyRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ProcessRoute: ProcessRoute,
  SignupRoute: SignupRoute,
  TracksRoute: TracksRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from '../../src/router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
